name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Build and Analyze
        run: >
          xcodebuild clean build analyze
          -project "Front Row.xcodeproj"
          -scheme "Front Row"
          CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
