name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Build and Analyze
        run: >
          xcodebuild clean build analyze
          -project "Front Row.xcodeproj"
          -scheme "Front Row"
          CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload string catalog
        uses: actions/upload-artifact@v4.3.1
        with:
          name: string-catalog
          path: "./Front Row/Localizable.xcstrings"

  crowdin:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4.1.4
        with:
          name: string-catalog
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload string catalog to Crowdin
        uses: crowdin/github-action@v1.19.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false

          source: Localizable.xcstrings
          translation: "%osx_locale%.xcstrings"

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
